### PR TITLE
Two new features for GirderUploadToItem

### PR DESCRIPTION
**Pull request by zachmullen**
* Allow other kwargs to be passed into the underlying girder_client upload method.
  This is useful for, e.g. passing a `reference` field on upload.
* Allow uploading a flat directory of files into a Girder item.

@kotfic @jbeezley These two features are required for a specific use case I'm working on right now that I wanted to go ahead and port to the modern g_w infrastructure. Namely, I'm generating a bunch of files that all need to be uploaded to an item with a `reference` value set. This is to gain feature parity with [this section](https://github.com/girder/girder_worker/blob/6457743facf3ce8aa4eab2ee0e5cee9e910830ba/girder_worker/plugins/girder_io/__init__.py#L190-L202) of the legacy girder_worker.

### CODE REVIEW

**Comment by kotfic** [comment]
@zachmullen This seems fine to me,  do you think you could add a ```girder_io_test.py``` to tests, write a test for this functionality and file an issue (assigned to me)  to write tests for transforms in girder_io?

**Comment by zachmullen** [comment]
Good call, as you can see adding some basic unit tests uncovered some silly bugs in the class:

* It called a nonexistent method `shutil.rm`
* It was referencing a member variable `self.delete_file` that was never being set.

PTAL!

**Comment by zachmullen** [comment]
Apparently our flake8 configuration is very pedantic about import order and spacing. Is that on purpose?

**Comment by kotfic** [comment]
@zachmullen this is something @jbeezley introduced on geonotebook,  while it is annoying to get correct at first,  it has a real benefit when it comes to identifying what ranges introduced what import dependencies. My slight preference is to keep it,  but even a simple counter argument could convince me otherwise.

LGTM!

**Comment by zachmullen** [comment]
I have no qualms with the rule -- my only complaint would be that the flake8 output related to it was unclear about exactly what the policy was. It said something like "import x should come before import y", but it left me to try and figure out why that order was being enforced since they had been alphabetical.

**Pull request merged**
