### PR TITLE
Make GirderUploadToFolder recursive

### PR DESCRIPTION
**Pull request by zachmullen**

### CODE REVIEW

**Comment by zachmullen** [comment]
I consider this a bugfix, since I think recursive folder upload would be the expectation for this transform.

**Comment by kotfic** [comment]
This makes sense to me,  can you add a test in girder_io_test.py?

**Comment by kotfic** [comment]
i think it's unlikely to be a real problem,  but should we consider symlink following behavior with directories?

**Comment by zachmullen** [comment]
Are you worried about cycles? What solution do you propose?

**Comment by zachmullen** [comment]
@kotfic done

**Pull request merged**
